name: Supabase Backup

on:
  schedule:
    - cron: "0 5 * * 1"   # Lunes 12AM Colombia (UTC-5)
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PostgreSQL 17 client
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/postgresql.gpg
          echo "deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Create backups
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          DATE=$(date +%F)

          # SQL plano
          pg_dump "$DATABASE_URL" > backup_$DATE.sql

          # Dump binario profesional
          pg_dump "$DATABASE_URL" \
            --format=custom \
            --no-owner \
            --no-privileges \
            -f backup_$DATE.dump

          # Comprimir ambos
          gzip backup_$DATE.sql
          gzip backup_$DATE.dump

          echo "SQL_FILE=backup_$DATE.sql.gz" >> $GITHUB_ENV
          echo "DUMP_FILE=backup_$DATE.dump.gz" >> $GITHUB_ENV

      - name: Upload to Google Drive
        uses: addnab/docker-run-action@v3
        with:
          image: rclone/rclone
          options: >
            -v ${{ github.workspace }}:/data
          run: |
            echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > /data/service_account.json

            rclone config create drive drive \
              scope=drive \
              service_account_file=/data/service_account.json

            rclone copy /data/${{ env.SQL_FILE }} drive:"Backups Asamblea"
            rclone copy /data/${{ env.DUMP_FILE }} drive:"Backups Asamblea"

#      - name: Cleanup old backups (keep 30 days)
#        uses: addnab/docker-run-action@v3
#        with:
#          image: rclone/rclone
#          options: >
#            -v ${{ github.workspace }}:/data
#          run: |
#            echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > /data/service_account.json

#           rclone config create drive drive \
#              scope=drive \
#              service_account_file=/data/service_account.json

#            rclone delete drive:"Backups Asamblea" --min-age 30d